### ISSUE TITLE
IF AUTH_CHANNEL . MAKE USER CANT SEND MSG IF NOT SUBCRIBE THE CHANNEL. AND SEND MSG U NEED TO SUB CHANNEL TO USE THIS BOT

### ISSUE THREAD

**Issue by ranmiella** [SpEcHiDe/NoPMsBot#17] opened 2020-10-02 12:23 UTC

**Comment by SpEcHiDe** [comment] 2020-10-07 13:33
closing this, since this is a duplicate of #14

**Closed as completed by SpEcHiDe** 2020-10-07 13:33 UTC
