### ISSUE TITLE
FEATURE REQUEST: BUTTON SUPPORT

### ISSUE THREAD

**Issue by Mikesew1320** [SpEcHiDe/NoPMsBot#13] opened 2020-09-21 14:06 UTC
Can you add ability to leave messages like files or any documentation which can be retrieved by the user using the button that are prepared by the bot admin?

To make it clear, see thr screenshot below. 

If it doesn't fit our bot target, take the idea and make it to fit our bot.😉

Thanks!

**Comment by SpEcHiDe** [comment] 2020-09-21 14:06
tldr: menubuilderbot 😬😑😑

**Comment by Mikesew1320** [comment] 2020-09-21 14:10
> tldr: menubuilderbot 😬😑😑

What do u mean bro? I didn't get it. tldr....?😀

**Comment by SpEcHiDe** [comment] 2020-10-07 13:30
closing this, since this is a duplicate of #14

**Closed as completed by SpEcHiDe** 2020-10-07 13:30 UTC
