### ISSUE TITLE
FEATURE REQUEST: AWAY FROM KEYBOARD (AFK) MODE

### ISSUE THREAD

**Issue by Mikesew1320** [SpEcHiDe/NoPMsBot#12] opened 2020-09-20 15:46 UTC
Can you add ability to leave set message for peoples who send messages when we are offline? Like .afk [myreason]

**Comment by hvydya** [comment] 2020-09-21 06:35
Hi! I'd like to work on this issue. Can you assign it to me?

**Comment by SpEcHiDe** [comment] 2020-10-07 13:31
closing this, since this is a duplicate of #14

@hvydya you can PR your changes when it is completed.

**Closed as completed by SpEcHiDe** 2020-10-07 13:31 UTC
Labels: documentation, enhancement, good first issue, help wanted
